[package]
name = "rdp_dvc_server"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies.windows]
windows = "0.57.0"
features = [
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_RemoteDesktop",
    "Win32_System_IO",
]
