<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.build.pre.props" />

  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <AssemblyName>Devolutions.MsRdpEx</AssemblyName>
    <PackageId>Devolutions.MsRdpEx</PackageId>
    <Version>1.0.0.0</Version>
    <Authors>mamoreau@devolutions.net</Authors>
    <Company>Devolutions</Company>
    <Description>Microsoft RDP Extensions</Description>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <OutputPath>$(CMakeOutputPath)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AxInterop.MSTSCLib/AxInterop.MSTSCLib.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Interop.MSTSCLib.Generated/Interop.MSTSCLib.Generated.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(CMakeOutputPath)/MsRdpEx.dll" DestinationFolder="$(OutputPath)" OverwriteReadOnlyFiles="true" Condition="Exists('$(CMakeOutputPath)/MsRdpEx.dll')" />
    <Copy SourceFiles="$(CMakeOutputPath)/MsRdpEx.pdb" DestinationFolder="$(OutputPath)" OverwriteReadOnlyFiles="true" Condition="Exists('$(CMakeOutputPath)/MsRdpEx.pdb')" />
  </Target>

  <ItemGroup>
    <Content Include="../Interop.MSTSCLib/Interop.MSTSCLib.dll" PackagePath="interop/legacy/Interop.MSTSCLib.dll" Pack="true" Visible="false" />
    <Content Include="$(OutputPath)/Interop.MSTSCLib.Generated.dll" PackagePath="interop/generated/Interop.MSTSCLib.Generated.dll" Pack="true" Visible="false" />
    <Content Include="$(OutputPath)/AxInterop.MSTSCLib.dll" PackagePath="interop/generated-winforms/AxInterop.MSTSCLib.dll" Pack="true" Visible="false" />
    <Content Include="../../dependencies/MsRdpEx/x86/MsRdpEx.dll" PackagePath="runtimes/win-x86/native/MsRdpEx.dll" Pack="true" Visible="false" />
    <Content Include="../../dependencies/MsRdpEx/x64/MsRdpEx.dll" PackagePath="runtimes/win-x64/native/MsRdpEx.dll" Pack="true" Visible="false" />
    <Content Include="../../dependencies/MsRdpEx/arm64/MsRdpEx.dll" PackagePath="runtimes/win-arm64/native/MsRdpEx.dll" Pack="true" Visible="false" />
    <Content Include="Devolutions.MsRdpEx.targets" PackagePath="build/Devolutions.MsRdpEx.targets" Pack="true" />
    <Content Include="Devolutions.MsRdpEx.targets" PackagePath="buildTransitive/Devolutions.MsRdpEx.targets" Pack="true" />
  </ItemGroup>

</Project>