<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <MsRdpExComInterop>Generated</MsRdpExComInterop>
    <MsRdpExGeneratedWinForms>true</MsRdpExGeneratedWinForms>
    <MsRdpExPackageVersion Condition="'$(MsRdpExPackageVersion)' == ''">1.0.0</MsRdpExPackageVersion>
    <RestoreAdditionalProjectSources Condition="'$(MsRdpExTestPackageSource)' != ''">$(MsRdpExTestPackageSource)</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Devolutions.MsRdpEx" Version="[$(MsRdpExPackageVersion)]" GeneratePathProperty="true" />
    <Reference Include="AxInterop.MSTSCLib">
      <HintPath>$(PkgDevolutions_MsRdpEx)\interop\generated-winforms\AxInterop.MSTSCLib.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>
</Project>
