name: native package
on: workflow_dispatch
jobs:
  build-native:
    name: native build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86, x64, arm64 ]

    steps:
      - name: Configure runner
        run: |
          Install-Module -Name VsDevShell -Force

      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Build Detours (${{matrix.arch}})
        shell: pwsh
        run: |
          Enter-VsDevShell ${{matrix.arch}}
          .\detours.ps1

      - name: Build MsRdpEx (${{matrix.arch}})
        shell: pwsh
        run: |
          $ArchDir = "${{matrix.arch}}"
          $BuildDir = "build-$ArchDir"
          $MsvcArch = @{"x86"="Win32";"x64"="x64";"arm64"="ARM64"}["${{matrix.arch}}"]
          cmake -G "Visual Studio 17 2022" -A $MsvcArch -DWITH_DOTNET=OFF -B $BuildDir
          cmake --build $BuildDir --config Release
          New-Item -ItemType Directory -Path "dependencies/MsRdpEx/$ArchDir" | Out-Null
          Copy-Item "$BuildDir/Release/MsRdpEx.dll" "dependencies/MsRdpEx/$ArchDir/MsRdpEx.dll"
          Copy-Item "$BuildDir/Release/MsRdpEx_Exe.exe" "dependencies/MsRdpEx/$ArchDir/MsRdpEx.exe"

      - name: Upload MsRdpEx (${{matrix.arch}})
        uses: actions/upload-artifact@v3
        with:
          name: MsRdpEx-${{matrix.arch}}
          path: dependencies/MsRdpEx/${{matrix.arch}}
